spring:
  config:
    import:
    - optional:file:../../.env[.properties]

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: frappe
  
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Désactive la création automatique par Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog.yaml
  
  security:
    oauth2:
      client:
        registration:
          authentik:
            client-id: ${OIDC_CLIENT_ID}
            client-secret: ${OIDC_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: ${OIDC_SCOPE}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          authentik:
            authorization-uri: ${OIDC_AUTHORIZATION_URI}
            token-uri: ${OIDC_TOKEN_URI}
            user-info-uri: ${OIDC_USER_INFO_URI}
            jwk-set-uri: ${OIDC_JWK_SET_URI}
            user-name-attribute: ${OIDC_USER_NAME_ATTRIBUTE}
  
logging:
  level:
    '[fr.inpt.frappe]': DEBUG

server:
  tomcat:
    max-http-response-header-size: 1048576  # 1MB
