#
# This is only used by the Liquibase Maven plugin 
# and is only used in development environments.
#

url=jdbc:postgresql://localhost:5432/frappe
username=postgres
password=postgres
driver=org.postgresql.Driver

changeLogFile=src/main/resources/db/changelog.yaml
referenceUrl=hibernate:spring:fr.inpt.frappe?dialect=org.hibernate.dialect.PostgreSQLDialect
