-- liquibase formatted sql

-- changeset db_init:20250323173836-1
CREATE TABLE comments (id UUID NOT NULL, content VARCHAR(255), document_id UUID, user_id UUID, CONSTRAINT "commentsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-2
CREATE TABLE documents (id UUID NOT NULL, description VARCHAR(255), title VARCHAR(255), subject_id BIGINT, CONSTRAINT "documentsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-3
CREATE TABLE majors (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, discontinued BOOLEAN NOT NULL, name VARCHAR(255), short_name VARCHAR(255), school_id BIGINT, CONSTRAINT "majorsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-4
CREATE TABLE minors (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), short_name VARCHAR(255), major_id BIGINT, CONSTRAINT "minorsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-5
CREATE TABLE schools (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT "schoolsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-6
CREATE TABLE subjects (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), semester INTEGER NOT NULL, teaching_unit_id BIGINT, CONSTRAINT "subjectsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-7
CREATE TABLE tags (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT "tagsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-8
CREATE TABLE tags_documents (tags_id BIGINT NOT NULL, documents_id UUID NOT NULL);

-- changeset db_init:20250323173836-9
CREATE TABLE teaching_units (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), minor_id BIGINT, CONSTRAINT "teaching_unitsPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-10
CREATE TABLE users (id UUID NOT NULL, firstname VARCHAR(255), lastname VARCHAR(255), year INTEGER NOT NULL, major_id BIGINT, minor_id BIGINT, school_id BIGINT, CONSTRAINT "usersPK" PRIMARY KEY (id));

-- changeset db_init:20250323173836-11
ALTER TABLE subjects ADD CONSTRAINT "FK1jlvab3bf3hhxl2yteiy4mdfj" FOREIGN KEY (teaching_unit_id) REFERENCES teaching_units (id);

-- changeset db_init:20250323173836-12
ALTER TABLE users ADD CONSTRAINT "FK213ftvghjrfok6n85ajm0pysj" FOREIGN KEY (minor_id) REFERENCES minors (id);

-- changeset db_init:20250323173836-13
ALTER TABLE users ADD CONSTRAINT "FK3gj5j7vnsoxf1wp9n5hsqdiq3" FOREIGN KEY (school_id) REFERENCES schools (id);

-- changeset db_init:20250323173836-14
ALTER TABLE majors ADD CONSTRAINT "FK5wvyo6mggqefc31rx2ilfhxlg" FOREIGN KEY (school_id) REFERENCES schools (id);

-- changeset db_init:20250323173836-15
ALTER TABLE comments ADD CONSTRAINT "FK8omq0tc18jd43bu5tjh6jvraq" FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset db_init:20250323173836-16
ALTER TABLE minors ADD CONSTRAINT "FKa5yfyuqj3tum065mroe1nqj8c" FOREIGN KEY (major_id) REFERENCES majors (id);

-- changeset db_init:20250323173836-17
ALTER TABLE comments ADD CONSTRAINT "FKccw7klbfv0lkycbtfxa53sqja" FOREIGN KEY (document_id) REFERENCES documents (id);

-- changeset db_init:20250323173836-18
ALTER TABLE teaching_units ADD CONSTRAINT "FKg97m9yhhddf3rajujm8w8n7qc" FOREIGN KEY (minor_id) REFERENCES minors (id);

-- changeset db_init:20250323173836-19
ALTER TABLE tags_documents ADD CONSTRAINT "FKhabi3tf4abyte7b88bksegsuv" FOREIGN KEY (documents_id) REFERENCES documents (id);

-- changeset db_init:20250323173836-20
ALTER TABLE users ADD CONSTRAINT "FKkw5ffx2ufp42oxqx7py9wa7nq" FOREIGN KEY (major_id) REFERENCES majors (id);

-- changeset db_init:20250323173836-21
ALTER TABLE tags_documents ADD CONSTRAINT "FKlx1q85duk2mddulguc8olfr4j" FOREIGN KEY (tags_id) REFERENCES tags (id);

-- changeset db_init:20250323173836-22
ALTER TABLE documents ADD CONSTRAINT "FKpby9dar20817f18ipuxmqf4x4" FOREIGN KEY (subject_id) REFERENCES subjects (id);

