-- liquibase formatted sql

-- changeset create_users_table:20250320225103-1
CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255), CONSTRAINT "usersPK" PRIMARY KEY (id));

