.docker:
  stage: docker
  image:
    name: moby/buildkit:rootless
    entrypoint: ["sh", "-c"]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
    # Default parameters
    TAG: export TAG=latest-$(date +%Y%m%d%H%m)
    PUSH: "false"
  interruptible: true
  before_script:
    - |
      mkdir -p ~/.docker && cat > ~/.docker/config.json <<EOF
      {
        "auths": {
          "$CI_REGISTRY": {
            "auth": "$(echo -n "$CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD" | base64)"
          }
        }
      }
      EOF
  script:
    - eval $TAG
    - |
      buildctl-daemonless.sh build \
          --frontend=dockerfile.v0 \
          --local context=. \
          --local dockerfile=. \
          --opt target=$TARGET \
          --output "type=image,name=$CI_REGISTRY_IMAGE/$TARGET:v$TAG,push=$PUSH"
    - |
      if [ "$PUSH" == "true" ]; then \
        echo "Successfully built and pushed $CI_REGISTRY_IMAGE/$TARGET:v$TAG"; \
      else \
        echo "Successfully built $CI_REGISTRY_IMAGE/$TARGET:v$TAG"; \
      fi
