.api:
  image: maven:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - cp .env.ci .env
    - cd apps/api

build:api:
  extends: .api
  stage: build
  services:
    - name: postgres:17
      alias: postgres
  variables:
    POSTGRES_DB: frappe
    POSTGRES_USER: frappe
    POSTGRES_PASSWORD: frappe
    DATABASE_URL: postgresql://frappe:frappe@postgres:5432/frappe
  script:
    - mvn compile
    - mvn verify -Pgenerate-docs -DskipTests
  artifacts:
    paths:
      - schema.json
    expire_in: 20 minutes

test:api:
  extends: .api
  needs:
    - job: build:api
  stage: test
  script:
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' target/site/jacoco/jacoco.csv
  coverage: /\d+.\d+ \% covered/
  services:
    - name: postgres:17
      alias: postgres
  variables:
    POSTGRES_DB: frappe
    POSTGRES_USER: frappe
    POSTGRES_PASSWORD: frappe
    DATABASE_URL: postgresql://frappe:frappe@postgres:5432/frappe
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: apps/api/target/site/jacoco/jacoco.xml

release:api:
  extends: .docker
  stage: release
  interruptible: false
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        TAG: export TAG=$(echo $CI_COMMIT_TAG)
        PUSH: "true"
