.api:
  image: maven:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script:
    - cp .env.ci .env
    - cd apps/api

build:api:
  extends: .api
  stage: build
  script:
    - mvn compile

test:api:
  extends: .api
  needs:
    - job: build:api
  stage: test
  script:
    - mvn test
  services:
    - name: postgres:17
      alias: postgres
  variables:
    POSTGRES_DB: frappe
    POSTGRES_USER: frappe
    POSTGRES_PASSWORD: frappe
    DATABASE_URL: postgresql://frappe:frappe@postgres:5432/frappe
